### ISSUE TITLE
Error in checkForRemoteErrors(val)

### ISSUE THREAD

**Issue by abuabara** [alexWhitworth/synthACS#1]
Hi. I have been able to pull data elements for creating synthetic data, but the derive command is returning an error that I don't know how to deal with. Please, check below the sequence I'm trying to use ... Thank you!

> br_geo <- acs::geo.make(state= "TX", county= "Brazos", tract= "*")
> br_dat <- pull_synth_data(2014, 5, br_geo)
> br_synthetic <- derive_synth_datasets(br_dat, leave_cores= 0)
Error in checkForRemoteErrors(val) : 
  one node produced an error: length of 'dimnames' [2] not equal to array extent

**Comment by alexWhitworth** [comment]
@abuabara Initial exploration of this error indicates a problem with the input data, see  `br_synthetic <- derive_synth_datasets(br_dat, parallel= FALSE)`, which generates a message from `synthACS:::synth_data_pov` about the data. I will need to dig in more deeply when I have time.

**Comment by alexWhitworth** [comment]
This is due to problematic input data. Specifically `"Census Tract 9800, Brazos County, Texas"` only has a total population count of 4 and no individuals reported in the poverty data. We need to exclude this census tract from the analysis:

```
br_geo <- acs::geo.make(state= "TX", county= "Brazos", tract= "*")
br_dat <- pull_synth_data(2014, 5, br_geo)

# identify and remove the problem datapoint
prob_idx <- which(unlist(br_dat$estimates$age_by_sex[, 1]) < 10)
br_dat$estimates <- lapply(br_dat$estimates, function(l, ind) {l[-ind, ]}, ind = prob_idx)
br_dat$standard_error <- lapply(br_dat$standard_error, function(l, ind) {l[-ind, ]}, ind = prob_idx)
br_dat$geography <- br_dat$geography[-prob_idx, ]

# now proceed as planned:
br_synthetic <- derive_synth_datasets(br_dat, leave_cores= 0) 
# alternatively: br_synthetic <- derive_synth_datasets(br_dat, parallel= FALSE)
```
